services:

  keycloak_auxiliar:
    image: quay.io/keycloak/keycloak:26.3.3
    ports:
      - '8081:8080'
    environment:
      KC_DB_URL_HOST: pgsql_keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
    command: start-dev
    networks:
      - auxiliar_services
    depends_on:
      - pgsql_keycloak
    restart: unless-stopped

  pgsql_keycloak:
    image: postgres:14.10
    environment:
        POSTGRES_DB: keycloak_db
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
    volumes:
        - pgsql_keycloak_data:/var/lib/postgresql/data
    networks:
        - auxiliar_services
    restart: unless-stopped

volumes:
  pgsql_keycloak_data:

networks:
  auxiliar_services:
    name: auxiliar_services
